### PR TITLE
Solve visual bug with chat input

### PR DESCRIPTION
**Pull request by Joao-Alves**
Redid pull request #55 only with the changes to the readme, but solving the same issue.

### CODE REVIEW

**Comment by Joao-Alves** [comment]
@victoryhb here is the new pull request that solves the same issue without the changes on the readme that cause the issue to revert on #59.

Do you need anything else on my side?

**Comment by Joao-Alves** [comment]
This pull request solves #54.

**Comment by fgdvir** [comment]
Merging. PR was approved but was reverted due to a small bug in the README.

**Comment by Joao-Alves** [comment]
@fgdvir can you bump the version to redeploy it to pip? If you want I can also submit another pull request

**Comment by ishaan-mehta** [comment]
Hi @Joao-Alves, this doesn't seem to actually solve #54 (using streamlit-option-menu==0.3.12) — any idea what might be going on?

**Pull request merged**
