### PR TITLE
Add `disabled` component option argument with streamlit appropriate styling

### PR DESCRIPTION
**Pull request by blipk**
Continuation of previous PR with styling issues fixed: 
https://github.com/victoryhb/streamlit-option-menu/pull/49

Please review @victoryhb 

image

I have updated the CSS to use an invert() filter so the colour will be visible (but faded) on various surroundings.

### CODE REVIEW

**Comment by victoryhb** [comment]
Is this the complete PR? I don't seem to find the newly added `disabled` option?

**Comment by blipk** [comment]
Hey thanks @victoryhb - I missed your reversion of the previous PR and was reconciling those changes back to this one - I missed a commit and the notes in the readme on my end here.

Should be all good now, but no rush if you want to leave open for review and testing for a few days.

**Comment by blipk** [comment]
Looking the same as original now. I have also improved documentation for the styling and added some extra class tags.

image

If you'd like to review and raise any thoughts before merging.

**Comment by victoryhb** [comment]
Seems alright, thanks!

**Pull request merged**
