### PR TITLE
Add 'disabled' option the same as standard streamlit components

### PR DESCRIPTION
**Pull request by blipk**
This adds the `disabled` kwarg to the component which will disable the buttons and set appropriate style when it is set to true.

Let me know if there are any issues with the PR @victoryhb

### CODE REVIEW

**Comment by victoryhb** [comment]
Hi Thanks for the commit! A couple of quick comments:
1. Let's not use any type hints in the code to keep the style consistent
2. Please add a description about the option in ReadMe.
3. I have no problem using a new formatter like Black, but if we do so please ensure all Python files follows this formatting.

**Comment by blipk** [comment]
Hi @victoryhb 

1. No problem.
2. Have updated the doc string and README.md
3. Thanks, the two .py files have been run through black with the line-length slightly increased from the default to 99, all other settings are default.

**Comment by victoryhb** [comment]
Looks good. Thanks!

**Comment by victoryhb** [comment]
After further testing, the new code doesn’t appear to work with multiple menus on the same page? Will need to be further tested. Reverting for now.

**Comment by blipk** [comment]
Hey @victoryhb 

Could you provide a screenshot and which browser you are using? I can fix that up.

On my end here with the default styling on your component it looks like this:
image

I used the same CSS properties that streamlit uses for its disabled option:
```
"cursor": "not-allowed"
"color": "rgba(250, 250, 250, 0.4)",
"border-color": "rgba(250, 250, 250, 0.2)",
```

I understand that your component supports custom styling though, so it might conflict with other styling a user applies - e.g. if they have a dark background it may be hard to see the text, if I change to a CSS filter instead of a fixed colour would you be open to testing and accepting another PR?

**Comment by victoryhb** [comment]
screencapture-172-31-8-219-8501-2023-09-19-22_33_21
The disabled menus from the example code appear as above on my machine.
It's important for the option's appearance to adapt to different color themes. If you can fix this problem and show that it works across different themes I would accept it again. Thanks!

**Pull request merged**
